name = "wechat-mp"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[d1_databases]]
binding = "WECHAT_MP_DB"
database_name = "wechat-mp-db"
database_id = "b3063753-bfa4-4172-9692-3f7a4459d621"

[[r2_buckets]]
binding = "WECHAT_MP_BUCKET"
bucket_name = "wechat-os"
